# Generated by Django 4.2.27 on 2025-12-28 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Comparativo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('sesion_conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo.sesionconteo', verbose_name='Sesión de Conteo Físico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comparativo de Inventario',
                'verbose_name_plural': 'Comparativos de Inventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemComparativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema1', models.IntegerField(default=0, verbose_name='Cantidad Sistema 1')),
                ('cantidad_sistema2', models.IntegerField(default=0, verbose_name='Cantidad Sistema 2')),
                ('cantidad_fisico', models.IntegerField(default=0, verbose_name='Cantidad Físico')),
                ('diferencia_sistema1', models.IntegerField(default=0, verbose_name='Diferencia Sistema 1')),
                ('diferencia_sistema2', models.IntegerField(default=0, verbose_name='Diferencia Sistema 2')),
                ('comparativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comparativos.comparativoinventario', verbose_name='Comparativo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item Comparativo',
                'verbose_name_plural': 'Items Comparativos',
                'unique_together': {('comparativo', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='InventarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('sistema1', 'Sistema 1'), ('sistema2', 'Sistema 2')], max_length=20, verbose_name='Sistema')),
                ('archivo', models.FileField(upload_to='inventarios_sistema/', verbose_name='Archivo de Inventario')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('comparativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='comparativos.comparativoinventario', verbose_name='Comparativo')),
            ],
            options={
                'verbose_name': 'Inventario de Sistema',
                'verbose_name_plural': 'Inventarios de Sistema',
                'unique_together': {('comparativo', 'sistema')},
            },
        ),
    ]
