# Generated by Django 4.2.27 on 2025-12-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparativos', '0001_initial'),
    ]

    operations = [
    ]
