# Generated by Django 4.2.27 on 2025-12-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparativos', '0003_remove_comparativoinventario_sesion_conteo'),
        ('conteo', '0004_rename_sesionconteo_to_conteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativoinventario',
            name='conteo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conteo.conteo', verbose_name='Conteo Físico'),
        ),
    ]
