# Generated by Django 4.2.27 on 2025-12-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparativos', '0004_comparativoinventario_conteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativoinventario',
            name='nombre_sistema1',
            field=models.CharField(default='Sistema 1', max_length=100, verbose_name='Nombre Sistema 1'),
        ),
        migrations.AddField(
            model_name='comparativoinventario',
            name='nombre_sistema2',
            field=models.CharField(default='Sistema 2', max_length=100, verbose_name='Nombre Sistema 2'),
        ),
    ]
