# Generated by Django 4.2.27 on 2025-12-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parejaconteo',
            name='color',
            field=models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('info', 'Cian'), ('secondary', 'Gris'), ('dark', 'Negro'), ('light', 'Claro')], default='primary', max_length=20, verbose_name='Color'),
        ),
    ]
