# Generated by Django 4.2.27 on 2025-12-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_parejaconteo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN de 4 dígitos para acceso al sistema', max_length=4, null=True, verbose_name='PIN de Acceso'),
        ),
    ]
