# Generated by Django 4.2.27 on 2025-12-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteo', '0004_rename_sesionconteo_to_conteo'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='sesion_conteo',
        ),
        migrations.AddField(
            model_name='reporte',
            name='conteo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conteo.conteo', verbose_name='Conteo'),
        ),
    ]
