# Generated by Django 4.2.27 on 2025-12-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_producto_atributo_producto_codigo'),
        ('conteo', '0005_alter_conteo_options_alter_conteo_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agregar', 'Agregar'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad_anterior', models.IntegerField(default=0, verbose_name='Cantidad Anterior')),
                ('cantidad_nueva', models.IntegerField(default=0, verbose_name='Cantidad Nueva')),
                ('cantidad_cambiada', models.IntegerField(default=0, verbose_name='Cantidad Cambiada')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='conteo.conteo', verbose_name='Conteo')),
                ('item_conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='conteo.itemconteo', verbose_name='Item de Conteo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Conteo',
                'verbose_name_plural': 'Movimientos de Conteo',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['-fecha_movimiento'], name='movimientos_fecha_m_29619c_idx'), models.Index(fields=['conteo', '-fecha_movimiento'], name='movimientos_conteo__b18d35_idx'), models.Index(fields=['usuario', '-fecha_movimiento'], name='movimientos_usuario_b9bd8d_idx')],
            },
        ),
    ]
