# Generated by Django 4.2.27 on 2025-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='atributo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Atributo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código'),
        ),
    ]
