# Generated by Django 4.2.27 on 2025-12-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_atributo_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
    ]
