# Generated by Django 4.2.27 on 2025-12-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
    ]
