# Generated by Django 4.2.27 on 2025-12-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_api',
            field=models.CharField(blank=True, help_text='ID del producto en la API externa', max_length=100, null=True, unique=True, verbose_name='ID API'),
        ),
    ]
