# Generated by Django 4.2.27 on 2025-12-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_pin'),
        ('productos', '0006_producto_id_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='parejas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Parejas de conteo asignadas para contar este producto', related_name='productos_asignados', to='usuarios.parejaconteo', verbose_name='Parejas Asignadas'),
        ),
    ]
