# Generated by Django 4.2.27 on 2025-12-28 17:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Sesión')),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_usuario1', to=settings.AUTH_USER_MODEL, verbose_name='Usuario 1')),
                ('usuario_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_usuario2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario 2')),
            ],
            options={
                'verbose_name': 'Sesión de Conteo',
                'verbose_name_plural': 'Sesiones de Conteo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Contada')),
                ('fecha_conteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Conteo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='conteo.sesionconteo', verbose_name='Sesión')),
                ('usuario_conteo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Contó')),
            ],
            options={
                'verbose_name': 'Item de Conteo',
                'verbose_name_plural': 'Items de Conteo',
                'ordering': ['-fecha_conteo'],
                'unique_together': {('sesion', 'producto')},
            },
        ),
    ]
