# Generated by Django 4.2.27 on 2025-12-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionconteo',
            options={'ordering': ['numero_conteo', '-fecha_inicio'], 'verbose_name': 'Sesión de Conteo', 'verbose_name_plural': 'Sesiones de Conteo'},
        ),
        migrations.AddField(
            model_name='sesionconteo',
            name='numero_conteo',
            field=models.IntegerField(choices=[(1, 'Conteo 1'), (2, 'Conteo 2'), (3, 'Conteo 3')], default=1, verbose_name='Número de Conteo'),
        ),
        migrations.AlterUniqueTogether(
            name='sesionconteo',
            unique_together={('nombre', 'numero_conteo')},
        ),
    ]
