# Generated by Django 4.2.27 on 2025-12-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteo', '0004_rename_sesionconteo_to_conteo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteo',
            options={'ordering': ['numero_conteo', '-fecha_inicio'], 'verbose_name': 'Conteo', 'verbose_name_plural': 'Conteos'},
        ),
        migrations.AlterField(
            model_name='conteo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Conteo'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='usuario_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_usuario1', to=settings.AUTH_USER_MODEL, verbose_name='Usuario 1'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='usuario_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_usuario2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario 2'),
        ),
        migrations.AlterField(
            model_name='itemconteo',
            name='conteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='conteo.conteo', verbose_name='Conteo'),
        ),
        migrations.AlterModelTable(
            name='conteo',
            table='conteo_sesionconteo',
        ),
    ]
