# Generated by Django 4.2.27 on 2025-12-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteo', '0005_alter_conteo_options_alter_conteo_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteo',
            name='parejas',
            field=models.ManyToManyField(blank=True, related_name='conteos', to='usuarios.parejaconteo', verbose_name='Parejas'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='usuario_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteos_usuario1', to=settings.AUTH_USER_MODEL, verbose_name='Usuario 1'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='usuario_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteos_usuario2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario 2'),
        ),
    ]
