# Generated by Django 4.2.27 on 2025-12-28 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteo', '0006_conteo_parejas_alter_conteo_usuario_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='conteo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='conteo',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AddField(
            model_name='conteo',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
    ]
